### ISSUE TITLE
Oprava ukolu

### ISSUE THREAD

**Issue by nothumbee** [Desjula/DU-baervne-palety#1]
Zadani splneno, super!

Jen jedna drobnost - [tady](https://github.com/Desjula/DU-baervne-palety/blob/f33c22c1fd3dbfe5aaffe7f267557a15c898ad13/src/index.jsx#L18) ti zustal puvodni kod, takze nektere palety jsou tam duplicitne.

**Comment by Desjula** [comment]
Už jsem to odstranila. Nebyla jsem si jistá jestli to tam nechat nebo ne, tak jsem to tam nechala. Teď už to je pryč.
